steps:
  - name: 'node'
    entrypoint: 'npm'
    id: 'npm-install'
    args: ['install']

  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'lint']
    waitFor: ['npm-install']

  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'test']
    waitFor: ['npm-install']
